#!/bin/sh
#
# A hook to enforce a commit message with a JIRA issue number in the commit message.
# The JIRA issue number is collected from the current branch name.
#
BRANCH_NAME="$(b=$(git symbolic-ref -q HEAD | sed -e 's/\(.*\)\/\(.*\)-\([0-9]*\)-\(.*\)$/[\2-\3]: \4/' ); { [ -n "$b" ] && echo ${b##refs/heads/}; } || echo HEAD)"

echo "branch:"
echo $BRANCH_NAME
echo $1, $2, $3

FILE_CONTENT=$(cat "$1")
case "$2,$3" in
  merge,)
    /usr/bin/perl -i.bak -ne 's/^/# /, s/^# #/#/ if /^Conflicts/ .. /#/; print' "$1" ;;

# ,|template,)
#   /usr/bin/perl -i.bak -pe '
#      print "\n" . `git diff --cached --name-status -r`
#	 if /^#/ && $first++ == 0' "$1" ;;

  *) ;;
esac


if [ x$2 = "xmessage" ]; then
	echo "${BRANCH_NAME}: ${FILE_CONTENT}" > $1
else
	echo "${BRANCH_NAME}": > $1
	echo "${FILE_CONTENT}" >> $1
fi

